### ISSUE TITLE
[HINDSIGHT] Charter lacks clarity on the longer term vision, intended audience, audience-specific goals and objectives, ....

### ISSUE THREAD

**Issue by mwherman2000** [w3c/verifiable-credentials#33]
In general, a good charter document will include:
1. A longer term vision statement that guides the project from release to release, version to version ...an arrow pointing to some point on the horizon that specifically guides the current release N, plus release N+1
2. A clear statement (a commitment to the reader of the document) of who the intended/primary readers(s) are for the document. e.g. software architects and developers
3. A set of audience-specific set of goals and objectives that the current release N sets out to address (a further commitment to the reader)

**Background**

Quoting from http://www.echoes.com/msf/envisioning.html ...

> **Vision**
> There are six fundamental concepts and guiding principles that underlie the MSF project vision and scoping approach
> 
> 1. Peak performance begins with a commitment to vision
> 2. To produce great results, vision must exist and be communicated
> 3. A great project vision combines verbal and visual information
> 4. Vision is bounded by no preconceived limitations
> 5. The sustaining source of vision is business value
> 6. Vision guides shorter-range objectives (scope)
> 
> **Scope**
> Setting the scope means that the needs of a diverse set of end users must be balanced against each other as well as other priorities set down by management. Several variables may impact the potential success of the project, including costs, resources, schedule functionality, and reliability. The key is finding the right balance between these variables

**Comment by brentzundel** [comment]
This issue relates to the recently approved charter. There is no action that can be taken at this time, nor can the issue be transferred to the appropriate repository (https://github.com/w3c/vc-wg-charter) as it has been archived.

Closing.
