### ISSUE TITLE
How to ensure that the verifiable credential issuer is a legitimate issuer?

### ISSUE THREAD

**Issue by vanuverma** [w3c/verifiable-credentials#34]
Hello All,
First of all, apologies for putting this question in issues as I can't seem to find a page to ask the question.

**My question is:**
As a verifiable credential issuer is allowed to register one or more DID's in decentralized (distributed) ledger, how can a verifier be assured that the credential that it is verifying, is actually issued by a legitimate issuer?

**Below is an example to clarify the question:**

Let's say, a motor driving licence issuing agency (MDLA) registered themselves into a decentralized (distributed) ledger with DID value as "did:example:mdla1". They have also registered the driving licence schema along with that DID which looks like below (over simplified example):

```
"schema_json":{
  "id":"mdla:drivinglicence:schema:v:1.0",
  "name":"Driving Licence",
  "attrNames":["full_name", "credential_created_date", "start_date", "end_date"],
  ....
}
```

Now, let's say I want to tamper with the verifiable driving licence credential. And to do that, I do register myself in a decentralized (distributed) ledger with DID as "did:example:mdla2" along with the same credential schema as above (only changed the ID to be my preferred ID). And later populate a fake verifiable driving licence using that. 

Now, when I present the credential (that I have created by myself) to a person (say a police officer) to verify, how the verifier will know that the credential is issued by me (thus it is fake) and not issued by the actual authority (MDLA)?

As per my understanding so far, my DID (did:example:mdla2) will have my public key associated with it and I have digitally signed my verifiable driving licence credential using my private key, therefore the signature should be verified without any issue.

Please help me clarify this confusion or point me to some resource where I can get a better understanding. 

Again, apologies for putting this question in here.
Thank you.

**Comment by talltree** [comment]
The short answer to your question is that verifiers either: a) already know
the authoritative DID of the issuer, or b) verifiers can verify the DID
with a trust registry (see the ToIP Trust Registry Protocol Specification
<https://docs.google.com/document/d/1ZGXUB0oODHO66PQkO66-fbAu6f7sVVToOz3Q8RNG0fs/edit?usp=sharing>)
or via set of credentials chaining back to a governing authority the
verifier trusts (see Authentic Chained Data Containers
<https://wiki.trustoverip.org/display/HOME/ACDC+%28Authentic+Chained+Data+Container%29+Task+Force>
).

=Drummond

   1. The holder can give the verifier a set of chained credentials that
   chain back to a

**Comment by vanuverma** [comment]
Thank you so much for the answer and links. Much appreciated.
