### ISSUE TITLE
2021-12-15-action1: add a sentence or two to PR [https://github.com/w3c/vc-data-model/pull/847](https://github.com/w3c/vc-data-model/pull/847). (David Chadwick)

### ISSUE THREAD

**Issue by iherman** [w3c/verifiable-credentials#35]
add a sentence or two to PR [https://github.com/w3c/vc-data-model/pull/847](https://github.com/w3c/vc-data-model/pull/847). (David Chadwick) ([see details](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-12-15-vcwg#action1))

**Comment by brentzundel** [comment]
This has been done and is reflected in the current text of the PR
