### ISSUE TITLE
Issue with the meeting minutes page

### ISSUE THREAD

**Issue by xfq** [w3c/verifiable-credentials#52]
On https://w3c.github.io/verifiable-credentials/ , if I click "[more...](https://w3c.github.io/verifiable-credentials/Meetings/Minutes/)" under "[Meeting Minutes](https://w3c.github.io/verifiable-credentials/Meetings/Minutes/)", the visited page doesn't have any styling.

**Comment by brentzundel** [comment]
The link you are using is a github preview. The actual page is here https://www.w3.org/2017/vc/WG/
